# This file generates the GitHub Actions matrix.
include:
  - board: seeeduino_xiao_ble
    shield: LiNEA40_left rgbled_adapter
    artifact-name: LiNEA40_left_peripheral
  - board: seeeduino_xiao_ble
    shield: LiNEA40_right rgbled_adapter
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: LiNEA40_right_central_studio
  - board: seeeduino_xiao_ble
    shield: settings_reset
    artifact-name: settings_reset-seeeduino_xiao_ble
